baseURL = 'https://example.com'
languageCode = ''
title = 'Magnolia Default' # This can get overwritten by the single language files
defaultContentLanguage = 'en'
# defaultContentLanguageInSubDir = true
enableRobotsTXT = true
theme = "Magnolia"
googleAnalytics = ""

#  BLOG  #
[taxonomies]
# Delete line below to remove tags rendering
tag = "tags"

# Developer area
[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"
      [[module.mounts]]
      source = 'assets'
      target = 'assets'
  
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true