disabled = false
languageCode = 'it-IT'
languageName = 'Italiano'
title = 'Magnolia' # This will go in the Header as well
copyright = "Designed by Ludovico Caluori 🎨" # Please leave this here to give me some credit for my work, or BuyMeACoffee and change or remove the copyrightlink below :)
contentDir = "content/it"

# Change single params to false to remove from rendering
[params]
  subtitle = "Free Hugo theme" # This goes in the header and in the site title
  copyrightLink = "https://github.com/ololiuhqui"
  # PAGES
  [params.homepage]
    # Notice that SEO meta tags (what appears in google search results) can be set
    # in individual pages frontmatters `/content/<page>`
    ###
    preTitle = 'Free Hugo theme'
    title = "Magnolia"
    # You can use some markdown safely here as long as you don't include line breaks
    intro= """
*"La libertà ci rende esseri umani migliori e ci fa migliorare più velocemente il nostro status di razza collettiva "*.

**Un tema Hugo semplice, completamente personalizzabile e multilingue pensato per i professionisti e le piccole imprese **.

Ho costruito questo tema pensando alla semplicità, è piccolo e facilmente **personalizzabile, reattivo, modulare e multilingua**. Ma lascia anche spazio a una personalizzazione più approfondita, poiché utilizza **Bootstrap** e **SCSS**.

Qui c'è la [pagina github del tema](https://github.com/ololiuhqui/magnolia-free-hugo-theme), a cui si dovrebbe fare riferimento se si cercano ulteriori dettagli, ricordati di lasciare una stellina al repo!

Guardate cosa è in grado di fare questo tema nella pagina delle caratteristiche e vedete un bellissimo esempio di pagina dei contatti qui sotto.
        """
    mainButton = "Caratteristiche"
    mainButtonRef = "caratteristiche" # Just write the name or slug of the page here
    secondButton = "Contatti"
    secondButtonRef = "contatti" # Just write the name of the pages here
    [params.homepage.description]
    enabled = true
    secondTitle = "Come usare questo tema"
    paragraph = """ #### Installare 📥
- Installare hugo extended, seguendo [la guida ufficiale all'installazione](https://gohugo.io/installation/).

- Creare un nuovo sito: `hugo new site <nome sito>`.

- Clonare il repo del tema come sottomodulo nel nuovo sito:`git init && git submodule add --depth=1 https://github.com/ololiuhqui/magnolia-free-hugo-theme themes/Magnolia`

- Copiare il contenuto di "exampleSite" nel proprio sito, dalla cartella principale del nuovo sito: `cp -rv themes/Magnolia/exampleSite/* ./`

- Elimina il tuo `config.toml` di default dalla cartella root del tuo sito, le nuove configurazioni si troveranno in `config/_default`. Il file di configurazione principale è `config/_default/config.toml`, ma alcune variabili vengono definite o sovrascritte dai file di configurazioni delle singole lingue (es. `config/_default/languages/.en.toml`).

- Vedere l'anteprima del sito con `hugo serve -D`.

#### Personalizzare 🎨
- Utilizza i tuoi colori preferiti modificando le variabili di Bootstrap in `assets/scss/custom-variables.scss`.

- Modifica i file di configurazione aggiungendo i tuoi elementi alle pagine. È possibile modificare anche i nomi delle pagine del menù.

- Modifica i nomi, gli slug e le metadescrizioni delle pagine in `content/<language>/<page>.html`. Il file `_index.html` nella radice di ogni cartella della lingua dei contenuti è la homepage, fare riferimento a [Organizzazione dei contenuti] (https://gohugo.io/content-management/organization/).

- Cambia le immagini del sito web dalle cartelle `static` o `content` (alcune pagine (come la homepage e "office") usano [Page bundles](https://gohugo.io/content-management/page-bundles/)), si noti che il nome ed il formato (.webp) delle immagini deve essere lo stesso di quelle attualmente presenti nel sito di esempio.

#### Aggiungere nuove lingue 🚩

- Andare a `config/_default/languages`.
- Duplicare uno dei file di lingua, cambiare il tag della lingua e il nome del file (en, it, fr ecc.): questo dovrebbe essere conforme a [RFC 5646](https://gohugo.io/content-management/multilingual/). Utilizzare [RFC 5646 Language Tags List](https://gist.github.com/msikma/8912e62ed866778ff8cd) per una configurazione dei nomi dei file più rapida.
- Tradurre i valori delle variabili all'interno del file `.toml` in base alla lingua.
- Nella cartella `/content`, duplicare una delle cartelle delle lingue e cambiarne il nome in base alla nuova lingua, il nome deve essere conforme come al punto 2.
- Per ogni file `.html` in `/content`, è possibile modificare liberamente `title` (titolo della pagina) e `slug` (come apparirà il link della pagina). La `translationKey` deve rimanere intatta.
- Suggerisco vivamente di aggiornare anche il SEO nel frontmatter delle pagine in `/content` nella nuova lingua, in modo tale da avere dei metadata tradotti.

#### Pagina 404 personalizzata

Per aggiungere la pagina 404 personalizzata e farla funzionare su github pages, è necessario aggiungere manualmente il file nel root della cartella `/public` durante la costruzione del sito dopo aver eseguito `hugo`. Questo perché github pages cerca un modello 404 nella cartella principale del progetto, quindi è possibile avere una sola pagina 404 per tutte le lingue. Per creare un link simbolico alla versione 404 inglese, che sarà poi usata come 404 predefinita una volta che il sito sarà in hosting, dopo aver eseguito `hugo` eseguire `ln -s public/en/404/index.html public/404.html`.

**Fare riferimento a [themepage]()/[github](https://github.com/ololiuhqui/magnolia-free-hugo-theme) per maggiori dettagli. #TODO.**
        """
    paragraph2= "" #You can use markdown to define your first paragraph look, but in case this isn't enough, here there's a secoind paragraph


[params.office]
  title = "Uffici"
 description = "Questa pagina può essere facilmente personalizzata con l'aggiunta di un link a Google Maps per ottenere indicazioni stradali verso il luogo dell'attività."
 buttonText = "Indicazioni" 
 buttonLink = "https://maps.app.goo.gl/LzsPzRkTYSZ8SF3y8" # google maps "share" link here (for button)
 mapLink = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d382266.44569392945!2d-76.55832397784323!3d41.53770983690751!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c4d93a77484bbb%3A0xfff27920ab9bfae8!2sScranton%2C%20Pennsylvania%2C%20Stati%20Uniti!5e0!3m2!1sit!2sit!4v1716459350324!5m2!1sit!2sit" # google maps "embed" link here

[params.contacts]
  title = "Contattaci!"
  formCallToAction = "Questa è una pagina di esempio \"contattaci\"; è possibile ricevere le risposte dei moduli su FormSpree (gratis)."
  socialCallToAction = "Puoi aggiungere i tuoi link ai social media qui sotto!" # These are the same as in [params.social]
  [params.contacts.form]
    formspreeLink = "https://yourformspreelink.com" #subscribe to formspree and add the link for the form here
    firstname = "Nome*"
    lastname = "Cognome*"
    email = "E-mail*"
    phone = "Numero di telefono*"
    Inquiry = "Richiesta*"
    checkbox = " accetto che i miei dati siano trattati in conformità alla legge*"
    submitBtn = "Invia"
[params.services]
  title = "Caratteristiche"
  description = """ Ho costruito questo tema pensando alla semplicità: è piccolo e facilmente personalizzabile, reattivo, modulare e multilingue. Ma lascia anche spazio ad ulteriori personalizzazioni approfondite, poiché utilizza Bootstrap e SCSS.
  Questa pagina mostra anche un esempio di come si possono cambiare i nomi delle pagine del sito: Il sito utilizzerà il layout `services.html`, ma la pagina si chiamerà "Caratteristiche" e il link userà il relative permalink `/caratteristiche`."""
  [params.services.list]
    # You can add as much params.services.list.<N> as you like
    [params.services.list.0]
      title= "Responsività"
      description= "Il tema è completamente reattivo e si visualizza perfettamente su ogni dimensione dello schermo."
    [params.services.list.01]
      title = "Modularità"
      description= "Nascondi e mostra alcuni elementi facilmente dal file di configurazione"
    [params.services.list.02]
      title = "Multilingual"
      description= "a lingua predefinita dei contenuti è l'inglese (può essere cambiata), ma è possibile aggiungere tutte le lingue che si desidera in modo molto semplice; il tema include un esempio di lingua italiana e un menu a tendina per passare facilmente da una lingua all'altra. I permalink possono essere localizzati in ogni lingua (ad esempio, si può avere `/contatti` per l'inglese e `/contatti` per l'italiano)."
    [params.services.list.03]
      title = "Personalizzabile"
      description= "Il contenuto della pagina può essere personalizzato all'interno dei file di configurazione. Alcune variabili possono essere cambiate dai file SCSS."
    [params.services.list.04]
      title = "SEO ready"
      description= "Ogni pagina in /content ha una *meta descrizione* facilmente personalizzabile e un *meta titolo* unico per una migliore e più facile indicizzazione. Il tema userà l'immagine `static/img/meta-image` come meta-immagine per Google, Meta e X."
    [params.services.list.05]
      title = "Google Analytics integrato"
      description= "Inserite il vostro tag Google Analytics nel file `config.toml` e sarete pronti a monitorare facilmente le prestazioni del vostro sito."
    [params.services.list.06]
      title = "Google Maps Incluso"
      description= "La pagina dei contatti può essere facilmente personalizzata con l'aggiunta di un link a Google Maps per ottenere indicazioni stradali verso la sede dell'attività."


  
# /. PAGES

[params.socials]
  enabled = true # enables/disables the whole social section in the footer
  callToAction= "Connettiti con noi sui social media >"
      [[params.socials.link]]
        name = "github"
        link = "https://github.com/ololiuhqui/magnolia-free-hugo-theme"
      [[params.socials.link]]
        name = "linkedin"
        link = ""
      [[params.socials.link]]
        name = "whatsapp"
        link = ""
      # You can add other socials here by copypasting the above section and
      # selecting the right name for the icon from here https://icons.getbootstrap.com/

[params.schedules] # Time schedules (eg. your office openming hours)
  enabledFooter = false # This will add the schedules on the footer too
  enabledContacts = true # This will add the schedule to the contact page
  title = "Office hours" # For contacts page only
  [params.schedules.days]
  # Use something like "Monday: 9-13" for each day
  # if left empty it is disabled (default)
    day1 = "Lunedì: 9:00 – 19:00"
    day2 = "Martedì: 9:00 – 19:00"
    day3 = "Mercoledì: 9:00 – 19:00"
    day4 = "Giovedì: 9:00 – 19:00"
    day5 = "Venerdì: 9:00 – 19:01"
    day6 = ""
    day7 = ""

[params.footer]
  extraDescription1 = "Straight outta Scranton city"
  extraDescription2 = "VAT No. 0000000000"
  [params.footer.navigate]
  heading = "Naviga"   
  [params.footer.contacts]
  enabled = true # enables/disables the whole contacts section in footer
  heading = "Contatti"
  address = "Scranton 2865 Pouros Corners 55441-0788"
  mail = "dundermifflin@fakemail.com"
  mail2 = "dundermifflinorders@fakemail.com"
  phone = "+00 0000000"
  
[params.notfound]
  title = "404, page not found" # text for 404 page

[menus]
# PageRef should refer to the "translationKey" in `/content/<page>` frontmatter, names can be changed freely
  [[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "caratteristiche"
  pageRef = "/services"
  weight = 2
  [[menus.main]]
  name = "Uffici"
  pageRef = "/office"
  weight = 3
  [[menus.main]]
  name = "Contatti"
  pageRef = "/contacts"
  weight = 4